### ISSUE TITLE
Depricate package

### ISSUE THREAD

**Issue by ghost** [manaflair/redux-batch#18]
Needs to move on to a new maintainer, if this is even needed in 2019 given packages like Saga and RxObserveable

**Comment by arcanis** [comment]
Yes, we desperately need a new maintainer to merge "update readme".

**Comment by ghost** [comment]
Now I'm just convinced this doesn't need to exist in 2019's ecosystem.

**Comment by arcanis** [comment]
Given how helpful you are, and given that from a cursory glance this isn't the only repository you bless with your nice advices, I'm gonna make you a favor and prevent you from contributing any more.

So you got what you wanted: it's like this repo was archived, but only for your very person 😉
