### ISSUE TITLE
Preset es2015 - Usage in react native

### ISSUE THREAD

**Issue by Noitidart** [manaflair/redux-batch#5]
Hi there,
I absolutely loved your batching method in the web. I am trying to bring it to react-native but am having issues.

The error I am getting is: Couldn't find preset es2015 relative to directory.

![](http://i.imgur.com/9dzFiVi.png)

This is my code, may you please advise if I did things right, I am using redux-thunk along with hydrating reducers with initial state in an object caled `HYDRANT`:

```
import { applyMiddleware, combineReducers, compose, createStore } from "redux";
import { reduxBatch }  from '@manaflair/redux-batch';
import thunk from 'redux-thunk';

import HYDRANT from "../hydrant/hydrant";
import pages from "../reducers/pages";

const reducer = combineReducers({ pages });
const store = createStore(reducer, HYDRANT, compose(reduxBatch, applyMiddleware(thunk), reduxBatch));

export default store;
```

**Comment by arcanis** [comment]
It seems like you're running babel on the node_modules packages, which is unnecessary (and actually harmful, since the required preset are only installed in development mode) in the case of redux-batch since the files should already be transpiled.

**Comment by Noitidart** [comment]
Thanks very much for the super fast reply sir! This is standard `react-native init` project. :( I didn't change babel around. :( I will try adding ignore node_modules to babelrc and update you on how it goes. :)

Does my redux-thunk and hydrant usage look right with redux-batch?

Thank you sir!

**Comment by arcanis** [comment]
Looks fine to me! Let me know if you manage to fix it - if not I'm might take a look at it myself, but unfortunately not before a few days / weeks :(

**Comment by Noitidart** [comment]
Thanks sir I'll keep you updated.
