### ISSUE TITLE
currentListeners is not defined

### ISSUE THREAD

**Issue by sumitpal29** [manaflair/redux-batch#7]
Hi,
In your reduxBatch function, the declaration 
`let currentListeners = currentListeners; `
is throwing error. I think it should be 
`let currentListeners = nextListeners;`
Please have a look and do the changes if required.

Thanks.

**Comment by arcanis** [comment]
Hm, you're right. Fortunately, it initializes `currentListener` to `undefined`, which seems to be the right initialization value. Does it break something on your side?
